import { Source } from './types';

export const STARTER_SOURCES: Omit<Source, 'id' | 'created_at' | 'is_active'>[] = [
  // ==========================================
  // 1. MAINSTREAM NATIONAL (ENGLISH)
  // ==========================================
  {
    name: 'Indian Express',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://indianexpress.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Times of India — Top Stories',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Times of India — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms',
    language: 'en',
    region: 'national',
  },
  {
    name: 'NDTV — Latest',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://feeds.feedburner.com/ndtvnews-latest',
    language: 'en',
    region: 'national',
  },
  {
    name: 'NDTV — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:ndtv.com/india-news&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'national',
  },
  {
    name: 'News18',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.news18.com/rss/india.xml',
    language: 'en',
    region: 'national',
  },
  {
    name: 'India Today',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.indiatoday.in/rss/home',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Deccan Chronicle',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.deccanchronicle.com/rss_feed/',
    language: 'en',
    region: 'south-india',
  },
  {
    name: 'Deccan Herald',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.deccanherald.com/rss-feeds/feed/',
    language: 'en',
    region: 'karnataka',
  },
  {
    name: 'The Quint',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.thequint.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Print',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://theprint.in/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Free Press Journal',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.freepressjournal.in/rss/news',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Outlook India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:outlookindia.com/national&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'national',
  },
  {
    name: 'PIB (Press Information Bureau)',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://pib.gov.in/RssMain.aspx',
    language: 'en',
    region: 'national',
  },

  // ==========================================
  // 2. MAINSTREAM HINDI
  // ==========================================
  {
    name: 'Dainik Bhaskar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.bhaskar.com/rss-feed/1061/',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Amar Ujala',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.amarujala.com/rss/india-news.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Dainik Jagran',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.jagran.com/rss/news/national.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Navbharat Times',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://navbharattimes.indiatimes.com/rssfeedstopstories.cms',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'ABP News',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.abplive.com/home/feed',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Patrika',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.patrika.com/rss/national-news.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Jansatta',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.jansatta.com/feed/',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Zee News Hindi',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://zeenews.india.com/hindi/rss/india.xml',
    language: 'hi',
    region: 'national',
  },

  // ==========================================
  // 3. REGIONAL VERNACULAR (MAJOR INDIAN LANGUAGES)
  // ==========================================
  // Tamil
  {
    name: 'Puthiya Thalaimurai',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.puthiyathalaimurai.com/feed',
    language: 'ta',
    region: 'tamil-nadu',
  },
  {
    name: 'The Hindu Tamil',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.hindutamil.in/feed',
    language: 'ta',
    region: 'tamil-nadu',
  },
  {
    name: 'Dinamalar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.dinamalar.com/rss_news.asp',
    language: 'ta',
    region: 'tamil-nadu',
  },
  // Telugu
  {
    name: 'Eenadu',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:eenadu.net&hl=te&gl=IN&ceid=IN:te',
    language: 'te',
    region: 'andhra-telangana',
  },
  {
    name: 'Sakshi',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:sakshi.com&hl=te&gl=IN&ceid=IN:te',
    language: 'te',
    region: 'andhra-telangana',
  },
  // Kannada
  {
    name: 'Prajavani',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.prajavani.net/feed/',
    language: 'kn',
    region: 'karnataka',
  },
  {
    name: 'Vijay Karnataka',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=Vijay+Karnataka&hl=kn&gl=IN&ceid=IN:kn',
    language: 'kn',
    region: 'karnataka',
  },
  // Malayalam
  {
    name: 'Mathrubhumi',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.mathrubhumi.com/rss',
    language: 'ml',
    region: 'kerala',
  },
  {
    name: 'Onmanorama',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.onmanorama.com/rss/news/latest-news.rss',
    language: 'ml',
    region: 'kerala',
  },
  // Marathi
  {
    name: 'Lokmat',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.lokmat.com/rss/maharashtra.xml',
    language: 'mr',
    region: 'maharashtra',
  },
  {
    name: 'Sakal',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:esakal.com&hl=mr&gl=IN&ceid=IN:mr',
    language: 'mr',
    region: 'maharashtra',
  },
  // Gujarati
  {
    name: 'Divya Bhaskar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:divyabhaskar.co.in&hl=gu&gl=IN&ceid=IN:gu',
    language: 'gu',
    region: 'gujarat',
  },
  {
    name: 'Gujarat Samachar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:gujaratsamachar.com&hl=gu&gl=IN&ceid=IN:gu',
    language: 'gu',
    region: 'gujarat',
  },
  // Bengali
  {
    name: 'Anandabazar Patrika',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:anandabazar.com&hl=bn&gl=IN&ceid=IN:bn',
    language: 'bn',
    region: 'west-bengal',
  },
  {
    name: 'Ei Samay',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:eisamay.com&hl=bn&gl=IN&ceid=IN:bn',
    language: 'bn',
    region: 'west-bengal',
  },

  // ==========================================
  // 4. GRASSROOTS & INDEPENDENT JOURNALISM
  // ==========================================
  {
    name: 'The Wire',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://thewire.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Scroll.in',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://scroll.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Newslaundry',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.newslaundry.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The News Minute',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.thenewsminute.com/feeds/tnm-all-stories',
    language: 'en',
    region: 'south-india',
  },
  {
    name: 'Article 14',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://article-14.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Mooknayak',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://themooknayak.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Newsclick',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.newsclick.in/rss.xml',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Down To Earth',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.downtoearth.org.in/rss',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Gaon Connection',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.gaonconnection.com/feed',
    language: 'hi',
    region: 'rural-india',
  },
  {
    name: 'Khabar Lahariya',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:khabarlahariya.org&hl=hi&gl=IN&ceid=IN:hi',
    language: 'hi',
    region: 'rural-india',
  },
  {
    name: 'Behanbox',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://behanbox.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Maktoob Media',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://maktoobmedia.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'EastMojo',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://eastmojo.com/feed/',
    language: 'en',
    region: 'north-east',
  },
  {
    name: 'The Caravan',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://caravanmagazine.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Leaflet',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:theleaflet.in&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'national',
  },

  // ==========================================
  // 5. FACT CHECKERS
  // ==========================================
  {
    name: 'Alt News',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.altnews.in/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'BOOM Live',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.boomlive.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Newschecker',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://newschecker.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Factly',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://factly.in/feed/',
    language: 'en',
    region: 'national',
  },

  // ==========================================
  // 6. CIVIC DISCOURSE & PUBLIC OPINION
  // ==========================================
  {
    name: 'Youth Ki Awaaz',
    lane: 'discourse',
    type: 'rss',
    feed_url: 'https://www.youthkiawaaz.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Sabrang India',
    lane: 'discourse',
    type: 'rss',
    feed_url: 'https://sabrangindia.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Citizen',
    lane: 'discourse',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:thecitizen.in&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Indian Express Explained',
    lane: 'discourse',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:indianexpress.com/article/explained&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'national',
  },
  {
    name: 'r/india',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/india/.rss',
    language: 'en',
    region: 'national',
  },
  {
    name: 'r/IndiaSpeaks',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/IndiaSpeaks/.rss',
    language: 'en',
    region: 'national',
  },
  {
    name: 'r/delhi',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/delhi/.rss',
    language: 'en',
    region: 'delhi',
  },
  {
    name: 'r/bangalore',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/bangalore/.rss',
    language: 'en',
    region: 'bengaluru',
  },
  {
    name: 'r/mumbai',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/mumbai/.rss',
    language: 'en',
    region: 'mumbai',
  },

  // ==========================================
  // 7. INTERNATIONAL OUTLETS COVERING INDIA
  // ==========================================
  {
    name: 'BBC News — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://feeds.bbci.co.uk/news/world/asia/india/rss.xml',
    language: 'en',
    region: 'international',
  },
  {
    name: 'The Guardian — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.theguardian.com/world/india/rss',
    language: 'en',
    region: 'international',
  },
  {
    name: 'Reuters — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:reuters.com+India&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'international',
  },
  {
    name: 'Bloomberg — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:bloomberg.com+India&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'international',
  },
  {
    name: 'Al Jazeera — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:aljazeera.com+India&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'international',
  },
  {
    name: 'Deutsche Welle (DW) — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:dw.com+India&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'international',
  },
  {
    name: 'The Diplomat — South Asia',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:thediplomat.com+India&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'international',
  },
  {
    name: 'Rest of World — India',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:restofworld.org+India&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'international',
  },

  // ==========================================
  // 8. DOMESTIC FINANCIAL & NATIONAL EXPANSION
  // ==========================================
  {
    name: 'Hindustan Times',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Economic Times',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://economictimes.indiatimes.com/rssfeedstopstories.cms',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Livemint',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.livemint.com/rss/news',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Business Standard',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.business-standard.com/rss/home_page_top_stories.rss',
    language: 'en',
    region: 'national',
  },
  {
    name: 'PARI (Rural India)',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://news.google.com/rss/search?q=site:ruralindiaonline.org&hl=en-IN&gl=IN&ceid=IN:en',
    language: 'en',
    region: 'rural-india',
  },
  {
    name: 'The Wire Hindi',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://thewirehindi.com/feed/',
    language: 'hi',
    region: 'national',
  },
];

// Resilient syndication fallbacks for Cloudflare-protected, WAF-blocked, or malformed feeds
export const FEED_FALLBACKS: Record<string, string> = {
  'BBC News — India': 'https://news.google.com/rss/search?q=site:bbc.com/news/world/asia/india&hl=en-IN&gl=IN&ceid=IN:en',
  'The Guardian — India': 'https://news.google.com/rss/search?q=site:theguardian.com/world/india&hl=en-IN&gl=IN&ceid=IN:en',
  'Hindustan Times': 'https://news.google.com/rss/search?q=site:hindustantimes.com/india-news&hl=en-IN&gl=IN&ceid=IN:en',
  'Economic Times': 'https://news.google.com/rss/search?q=site:economictimes.indiatimes.com&hl=en-IN&gl=IN&ceid=IN:en',
  'Livemint': 'https://news.google.com/rss/search?q=site:livemint.com&hl=en-IN&gl=IN&ceid=IN:en',
  'Times of India — India': 'https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms',
  'NDTV — India': 'https://news.google.com/rss/search?q=site:ndtv.com/india-news&hl=en-IN&gl=IN&ceid=IN:en',
  'The Quint': 'https://news.google.com/rss/search?q=site:thequint.com&hl=en-IN&gl=IN&ceid=IN:en',
  'PIB (Press Information Bureau)': 'https://news.google.com/rss/search?q=site:pib.gov.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Dainik Bhaskar': 'https://news.google.com/rss/search?q=site:bhaskar.com&hl=hi&gl=IN&ceid=IN:hi',
  'The Wire': 'https://news.google.com/rss/search?q=site:thewire.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Scroll.in': 'https://news.google.com/rss/search?q=site:scroll.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Newslaundry': 'https://news.google.com/rss/search?q=site:newslaundry.com&hl=en-IN&gl=IN&ceid=IN:en',
  'The News Minute': 'https://news.google.com/rss/search?q=site:thenewsminute.com&hl=en-IN&gl=IN&ceid=IN:en',
  'Article 14': 'https://news.google.com/rss/search?q=site:article-14.com&hl=en-IN&gl=IN&ceid=IN:en',
  'Down To Earth': 'https://news.google.com/rss/search?q=site:downtoearth.org.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Gaon Connection': 'https://news.google.com/rss/search?q=site:gaonconnection.com&hl=hi&gl=IN&ceid=IN:hi',
  'Khabar Lahariya': 'https://news.google.com/rss/search?q=site:khabarlahariya.org&hl=hi&gl=IN&ceid=IN:hi',
  'The Caravan': 'https://news.google.com/rss/search?q=site:caravanmagazine.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Dainik Jagran': 'https://news.google.com/rss/search?q=site:jagran.com&hl=hi&gl=IN&ceid=IN:hi',
  'Navbharat Times': 'https://news.google.com/rss/search?q=site:navbharattimes.indiatimes.com&hl=hi&gl=IN&ceid=IN:hi',
  'ABP News': 'https://news.google.com/rss/search?q=site:abplive.com&hl=hi&gl=IN&ceid=IN:hi',
  'Patrika': 'https://news.google.com/rss/search?q=site:patrika.com&hl=hi&gl=IN&ceid=IN:hi',
  'Zee News Hindi': 'https://news.google.com/rss/search?q=site:zeenews.india.com/hindi&hl=hi&gl=IN&ceid=IN:hi',
  'Jansatta': 'https://news.google.com/rss/search?q=site:jansatta.com&hl=hi&gl=IN&ceid=IN:hi',
  'Eenadu': 'https://news.google.com/rss/search?q=site:eenadu.net&hl=te&gl=IN&ceid=IN:te',
  'Sakshi': 'https://news.google.com/rss/search?q=site:sakshi.com&hl=te&gl=IN&ceid=IN:te',
  'Vijay Karnataka': 'https://news.google.com/rss/search?q=Vijay+Karnataka&hl=kn&gl=IN&ceid=IN:kn',
  'Divya Bhaskar': 'https://news.google.com/rss/search?q=site:divyabhaskar.co.in&hl=gu&gl=IN&ceid=IN:gu',
  'Gujarat Samachar': 'https://news.google.com/rss/search?q=site:gujaratsamachar.com&hl=gu&gl=IN&ceid=IN:gu',
  'Anandabazar Patrika': 'https://news.google.com/rss/search?q=site:anandabazar.com&hl=bn&gl=IN&ceid=IN:bn',
  'Ei Samay': 'https://news.google.com/rss/search?q=site:eisamay.com&hl=bn&gl=IN&ceid=IN:bn',
  'Dinamalar': 'https://news.google.com/rss/search?q=site:dinamalar.com&hl=ta&gl=IN&ceid=IN:ta',
  'The Hindu Tamil': 'https://www.hindutamil.in/feed',
  'Onmanorama': 'https://news.google.com/rss/search?q=site:onmanorama.com&hl=en-IN&gl=IN&ceid=IN:en',
  'Free Press Journal': 'https://news.google.com/rss/search?q=site:freepressjournal.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Deccan Herald': 'https://news.google.com/rss/search?q=site:deccanherald.com&hl=en-IN&gl=IN&ceid=IN:en',
  'The Print': 'https://news.google.com/rss/search?q=site:theprint.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Outlook India': 'https://news.google.com/rss/search?q=site:outlookindia.com/national&hl=en-IN&gl=IN&ceid=IN:en',
  'The Citizen': 'https://news.google.com/rss/search?q=site:thecitizen.in&hl=en-IN&gl=IN&ceid=IN:en',
  'Business Standard': 'https://www.business-standard.com/rss/home_page_top_stories.rss',
  'The Wire Hindi': 'https://thewirehindi.com/feed/',
  'The Leaflet': 'https://news.google.com/rss/search?q=site:theleaflet.in&hl=en-IN&gl=IN&ceid=IN:en',
};
