import { Source } from './types';

export const STARTER_SOURCES: Omit<Source, 'id' | 'created_at' | 'is_active'>[] = [
  // --- MAINSTREAM ENGLISH ---
  {
    name: 'Indian Express',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://indianexpress.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Times of India — Top Stories',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Times of India — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://timesofindia.indiatimes.com/rss/India.cms',
    language: 'en',
    region: 'national',
  },
  {
    name: 'NDTV — Latest',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://feeds.feedburner.com/ndtvnews-latest',
    language: 'en',
    region: 'national',
  },
  {
    name: 'NDTV — India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://feeds.feedburner.com/NdtvNews-India',
    language: 'en',
    region: 'national',
  },
  {
    name: 'News18',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.news18.com/rss/india.xml',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Deccan Herald',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.deccanherald.com/rss-feeds/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Free Press Journal',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.freepressjournal.in/rss/news',
    language: 'en',
    region: 'national',
  },
  {
    name: 'India Today',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.indiatoday.in/rss/home',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Deccan Chronicle',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.deccanchronicle.com/rss_feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'PIB (Press Information Bureau)',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://pib.gov.in/RssMain.aspx',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Print',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://theprint.in/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Quint',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.thequint.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Outlook India',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.outlookindia.com/rss/main/magazine',
    language: 'en',
    region: 'national',
  },

  // --- MAINSTREAM HINDI ---
  {
    name: 'Dainik Jagran',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.jagran.com/rss/news/national.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Dainik Bhaskar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.bhaskar.com/rss-feed/1061/',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Amar Ujala',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.amarujala.com/rss/india-news.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Navbharat Times',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://navbharattimes.indiatimes.com/rssfeedstopstories.cms',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Zee News Hindi',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://zeenews.india.com/hindi/rss/india.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'ABP News',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.abplive.com/feed',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Patrika',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.patrika.com/rss/national-news.xml',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Jansatta',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.jansatta.com/feed/',
    language: 'hi',
    region: 'national',
  },

  // --- GRASSROOTS / INDEPENDENT ---
  {
    name: 'The Wire',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://thewire.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Scroll.in',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://scroll.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The News Minute',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.thenewsminute.com/feeds/tnm-all-stories',
    language: 'en',
    region: 'south-india',
  },
  {
    name: 'Article 14',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://article-14.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'The Mooknayak',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://themooknayak.com/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Newsclick',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.newsclick.in/rss.xml',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Youth Ki Awaaz',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.youthkiawaaz.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Down To Earth',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.downtoearth.org.in/rss',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Gaon Connection',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.gaonconnection.com/feed',
    language: 'hi',
    region: 'rural-india',
  },
  {
    name: 'Behanbox',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://behanbox.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Maktoob Media',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://maktoobmedia.com/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'EastMojo',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://eastmojo.com/feed/',
    language: 'en',
    region: 'north-east',
  },
  {
    name: 'The Caravan',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://caravanmagazine.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Newslaundry',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.newslaundry.com/feed',
    language: 'en',
    region: 'national',
  },

  // --- FACT CHECKERS ---
  {
    name: 'Alt News',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.altnews.in/feed/',
    language: 'en',
    region: 'national',
  },
  {
    name: 'BOOM Live',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://www.boomlive.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Newschecker',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://newschecker.in/feed',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Factly',
    lane: 'grassroots',
    type: 'rss',
    feed_url: 'https://factly.in/feed/',
    language: 'en',
    region: 'national',
  },

  // --- REGIONAL — TAMIL ---
  {
    name: 'Dinamalar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.dinamalar.com/rss_news.asp',
    language: 'ta',
    region: 'tamil-nadu',
  },
  {
    name: 'Puthiya Thalaimurai',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.puthiyathalaimurai.com/feed',
    language: 'ta',
    region: 'tamil-nadu',
  },
  {
    name: 'The Hindu Tamil',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.thehindu.com/news/feeder/default.rss',
    language: 'ta',
    region: 'tamil-nadu',
  },

  // --- REGIONAL — TELUGU ---
  {
    name: 'Eenadu',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.eenadu.net/rss_feeds/rss_feeds.aspx',
    language: 'te',
    region: 'andhra-telangana',
  },
  {
    name: 'Sakshi',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.sakshi.com/rss/rss.xml',
    language: 'te',
    region: 'andhra-telangana',
  },

  // --- REGIONAL — KANNADA ---
  {
    name: 'Prajavani',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.prajavani.net/feed/',
    language: 'kn',
    region: 'karnataka',
  },
  {
    name: 'Vijay Karnataka',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://vijaykarnataka.com/rss',
    language: 'kn',
    region: 'karnataka',
  },

  // --- REGIONAL — MALAYALAM ---
  {
    name: 'Onmanorama',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.onmanorama.com/rss/news/latest-news.rss',
    language: 'ml',
    region: 'kerala',
  },
  {
    name: 'Mathrubhumi',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.mathrubhumi.com/rss',
    language: 'ml',
    region: 'kerala',
  },

  // --- REGIONAL — BENGALI ---
  {
    name: 'Ei Samay',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://eisamay.com/rssfeedstopstories.cms',
    language: 'bn',
    region: 'west-bengal',
  },

  // --- REGIONAL — MARATHI ---
  {
    name: 'Lokmat',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.lokmat.com/rss/maharashtra.xml',
    language: 'mr',
    region: 'maharashtra',
  },

  // --- REGIONAL — GUJARATI ---
  {
    name: 'Divya Bhaskar',
    lane: 'mainstream',
    type: 'rss',
    feed_url: 'https://www.divyabhaskar.co.in/rss-feed/1220/',
    language: 'gu',
    region: 'gujarat',
  },

  // --- REDDIT DISCOURSE ---
  {
    name: 'r/india',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/india/hot.json',
    language: 'en',
    region: 'national',
  },
  {
    name: 'r/IndiaSpeaks',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/IndiaSpeaks/hot.json',
    language: 'en',
    region: 'national',
  },
  {
    name: 'r/indiatech',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/indiatech/hot.json',
    language: 'en',
    region: 'tech',
  },
  {
    name: 'r/AskIndia',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/AskIndia/hot.json',
    language: 'en',
    region: 'national',
  },
  {
    name: 'r/mumbai',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/mumbai/hot.json',
    language: 'en',
    region: 'mumbai',
  },
  {
    name: 'r/delhi',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/delhi/hot.json',
    language: 'en',
    region: 'delhi',
  },
  {
    name: 'r/bangalore',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/bangalore/hot.json',
    language: 'en',
    region: 'bengaluru',
  },
  {
    name: 'r/Chennai',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/Chennai/hot.json',
    language: 'en',
    region: 'chennai',
  },
  {
    name: 'r/hyderabad',
    lane: 'discourse',
    type: 'reddit',
    feed_url: 'https://www.reddit.com/r/hyderabad/hot.json',
    language: 'en',
    region: 'hyderabad',
  },

  // --- YOUTUBE GRASSROOTS ---
  {
    name: 'The Mooknayak YouTube',
    lane: 'grassroots',
    type: 'youtube',
    feed_url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCPpEFhzKm2KAQLV8fAEkE0Q',
    language: 'hi',
    region: 'national',
  },
  {
    name: 'Khabar Lahariya YouTube',
    lane: 'grassroots',
    type: 'youtube',
    feed_url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCkVhiEIbELKJFygdgMoLSuA',
    language: 'hi',
    region: 'uttar-pradesh',
  },
  {
    name: 'Newslaundry YouTube',
    lane: 'grassroots',
    type: 'youtube',
    feed_url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCHqSMOaB9bPCOoLmqjnq0Bw',
    language: 'en',
    region: 'national',
  },
  {
    name: 'Gaon Connection YouTube',
    lane: 'grassroots',
    type: 'youtube',
    feed_url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC4Qmb3VkPB96NQiWgpBzxNQ',
    language: 'hi',
    region: 'rural-india',
  },
];
